---
abstract: 'be like GETTY (without the insanity hopefully) -- use what drives his gears'
author:
  - 'Torsten Raudssus <torsten@raudss.us>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-GETTY
requires:
  App::Ack: 2.00
  App::CPAN::Fresh: 0.10
  App::cpanminus: 0
  Catalyst: 0
  Crypt::SSLeay: 0
  DBIx::Class: 0
  DBIx::Class::AlwaysUpdate: 0
  DateTime: 0.51
  Devel::NYTProf: 0
  Dist::Zilla: 4
  Dist::Zilla::PluginBundle::GETTY: 0.003
  IO::Socket::SSL: 0
  JSON: 2.12
  LWP::Protocol::https: 0
  Moo: 1.000003
  MooX: 0.101
  MooX::Cmd: 0.002
  MooX::Options: 3.71
  Moose: 2.0604
  Mozilla::CA: 0
  Plack: 0
  Pod::Weaver: 3.101631
  Reflex: 0.098
  Reflexive::Client::HTTP: 0.003
  Scalar::Util: 1.18
  Text::Markdown: v1.0.24
  Web::Simple: 0
  perl: 5.010001
resources:
  homepage: https://github.com/Getty/p5-task-belike-getty
  repository: https://github.com/Getty/p5-task-belike-getty.git
version: 20121001.000
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::GETTY/@Basic/GatherDir'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::GETTY/@Basic/PruneCruft'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::GETTY/@Basic/ManifestSkip'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::GETTY/@Basic/MetaYAML'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::GETTY/@Basic/License'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::GETTY/@Basic/Readme'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::GETTY/@Basic/ExtraTests'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::GETTY/@Basic/ExecDir'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::GETTY/@Basic/ShareDir'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::GETTY/@Basic/MakeMaker'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::GETTY/@Basic/Manifest'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::GETTY/@Basic/TestRelease'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::GETTY/@Basic/ConfirmRelease'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::GETTY/@Basic/UploadToCPAN'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@Author::GETTY/AutoVersion'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::GETTY/PkgVersion'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::GETTY/MetaConfig'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::GETTY/MetaJSON'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::GETTY/PodSyntaxTests'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::GETTY/Repository'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::GETTY/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::GETTY/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::GETTY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::GETTY/Git::CheckFor::CorrectBranch'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Author::GETTY/TestMoreWithSubtests'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@Author::GETTY/ChangelogFromGit'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@Author::GETTY/TaskWeaver'
      version: 0.101624
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::GETTY/@Git/Check'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::GETTY/@Git/Commit'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::GETTY/@Git/Tag'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::GETTY/@Git/Push'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300023
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300023
x_authority: cpan:GETTY
