---
abstract: 'be like GETTY (without the insanity hopefully) -- use what drives his gears'
author:
  - 'Torsten Raudssus <torsten@raudss.us>'
build_requires:
  Test::LoadAllModules: 0.021
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-GETTY
requires:
  App::Ack: 2.00
  App::CPAN::Fresh: 0.10
  App::cpanminus: 1.5018
  CPAN::Repository: 0.007
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::AutoCRUD: 2.122460
  Catalyst::Plugin::Captcha: 0
  Catalyst::Plugin::ChainedURI: 0.002
  Catalyst::Plugin::CustomErrorMessage: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: 5.90016
  Catalyst::View::Email::Template: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Config::INI: 0.019
  Crypt::SSLeay: 0
  DBIx::Class: 0.08200
  DBIx::Class::AlwaysUpdate: 0
  DBIx::Class::Candy: 0.002101
  DBIx::Class::EncodedColumn: 0.00011
  DBIx::Class::EncodedColumn::Crypt::Eksblowfish::Bcrypt: 0
  DBIx::Class::InflateColumn::DateTime: 0
  DBIx::Class::InflateColumn::Serializer: 0.03
  DBIx::Class::TimeStamp: 0
  Data::Printer: 0.33
  DateTime: 0.77
  DateTime::Format::Epoch: 0.13
  DateTime::Format::Human::Duration: 0.60
  DateTime::Format::Strptime: 1.52
  Devel::NYTProf: 0
  Dist::Data: 0.003
  Dist::Zilla: 4
  Dist::Zilla::PluginBundle::GETTY: 0.003
  Email::Valid: 0.185
  FCGI: 0.74
  File::ShareDir::ProjectDistDir: v0.3.2
  File::Temp: 0
  HTTP::Message: 0
  IO::All: 0.46
  IO::Socket::SSL: 0
  JSON: 2.53
  JSON::XS: 2.33
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Locale::Simple: 0.002
  Module::Data: 0.006
  Moo: 1.000003
  MooX: 0.101
  MooX::Cmd: 0.002
  MooX::HasEnv: 0
  MooX::Options: 3.71
  Moose: 2.0604
  MooseX::Getopt: 0
  MooseX::NonMoose: 0
  Mozilla::CA: 0
  Path::Class: 0.26
  Path::ScanINC: 0.002
  Plack: 1.0004
  Plack::Middleware::Debug: 0
  Reflex: 0.098
  Reflexive::Client::HTTP: 0.003
  Scalar::Util: 1.18
  String::ProgressBar: 0
  Template: 2.22
  Template::Provider::Encoding: 0
  Test::Dirs: 0
  Test::LoadAllModules: 0
  Test::More: 0
  Text::Markdown: v1.0.24
  Text::Xslate: 1.5018
  URI: 0
  URL::Encode: 0
  Web::Simple: 0.020
  YAML: 0.84
  perl: 5.010001
resources:
  homepage: https://github.com/Getty/p5-task-belike-getty
  repository: https://github.com/Getty/p5-task-belike-getty.git
version: 20130420.000
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::GETTY/@Basic/GatherDir'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::GETTY/@Basic/PruneCruft'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::GETTY/@Basic/ManifestSkip'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::GETTY/@Basic/MetaYAML'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::GETTY/@Basic/License'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::GETTY/@Basic/Readme'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::GETTY/@Basic/ExtraTests'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::GETTY/@Basic/ExecDir'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::GETTY/@Basic/ShareDir'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::GETTY/@Basic/MakeMaker'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::GETTY/@Basic/Manifest'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::GETTY/@Basic/TestRelease'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::GETTY/@Basic/ConfirmRelease'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::GETTY/@Basic/UploadToCPAN'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@Author::GETTY/AutoVersion'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::GETTY/PkgVersion'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::GETTY/MetaConfig'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::GETTY/MetaJSON'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::GETTY/PodSyntaxTests'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::GETTY/Repository'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::GETTY/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: '@Author::GETTY/TravisYML'
      version: 0.96
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::GETTY/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::GETTY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::GETTY/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Author::GETTY/TestsOfAuthorGETTY'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@Author::GETTY/ChangelogFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@Author::GETTY/TaskWeaver'
      version: 0.101624
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::GETTY/@Git/Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::GETTY/@Git/Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::GETTY/@Git/Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::GETTY/@Git/Push'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300033
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300033
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300033
x_authority: cpan:GETTY
